_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 52
                - 55
            "2":
                - 1
                - 52
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.9.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
